seed: 0
max_steps: 50
num_problems: 0 
num_process_evaluate: 12
timeout: 6
debug: False
assistant:
  min_tokens: 1
  max_tokens: 20
  generator: 
    model_name: meta-llama/Llama-3.1-8B-Instruct
    tokenizer_path: "meta-llama/Llama-3.1-8B-Instruct" 
    served: False
    # ports: [ 8000 ]
    llm:
      tensor_parallel_size: 1
      max_model_len: 16000
      enable_prefix_caching: True
    sampling:
      temperature: 0.7
      top_p: 0.8
      max_tokens: 2000
      logprobs: 1
      detokenize: False
human:
  max_tokens: 10
  reasoning_length: 300
  generator:
    model_name: google/gemma-3-27b-it 
    served: True
    ports: [ 8001 ]
    # ip: 100.83.210.2
    # sampling:
    #   temperature: 0.2
    #   top_p: 0.95
    #   max_tokens: 2000
    #   logprobs: 1
    #   detokenize: False
    sampling:
      temperature: 0.7
      top_p: 0.8
      max_tokens: 2000
      logprobs: 1
      detokenize: False
benchmark:
  not_fast: false
  release_version: "release_v6"
  start_date: "2024-08-01"
